package com.careercompass.jobanalysis.domain;

public enum JobAnalysisFailureCode {
    COMPARISON_STAGE_NOT_IMPLEMENTED,
    JOB_POSTING_PROVIDER_NOT_CONFIGURED,
    PROJECT_REPOSITORY_TREE_TRUNCATED,
    PROJECT_REPOSITORY_SNAPSHOT_INVALID,
    PROJECT_RESPONSIBILITY_MODEL_UNAVAILABLE,
    PROJECT_RESPONSIBILITY_EXTRACTION_INVALID_RESPONSE,
    EVIDENCE_COMPARISON_MODEL_UNAVAILABLE,
    EVIDENCE_COMPARISON_INVALID_RESPONSE,
    DEPENDENCY_UNAVAILABLE,
    DEPENDENCY_INVALID_RESPONSE,
    ALL_EXTRACTIONS_FAILED
}
